# Generated by Django 4.1.5 on 2023-01-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='arrival',
            new_name='arrival_flight',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='departure',
            new_name='departure_flight',
        ),
    ]
