# Generated by Django 4.1.5 on 2023-01-18 19:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_arrival_flight_arrival_flight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='aircraft',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='arrival_airport',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='arrival_flight',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_airport',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='departure_flight',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aircraft',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_flight', models.DateTimeField()),
                ('departure_flight', models.DateTimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aircraft +', to='main.aircraft')),
                ('arrival_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrival airport +', to='main.airport')),
                ('departure_airport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departure airport +', to='main.airport')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight +', to='main.flight')),
            ],
        ),
    ]
