# Generated by Django 4.1.5 on 2023-01-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aircraft_slug_airport_slug_flight_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='arrival_flight',
        ),
        migrations.RemoveField(
            model_name='management',
            name='departure_flight',
        ),
        migrations.AddField(
            model_name='management',
            name='arrival_flight_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='management',
            name='arrival_flight_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='management',
            name='departure_flight_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='management',
            name='departure_flight_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
