# Generated by Django 4.1.5 on 2023-01-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_management_arrival_flight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='manufacture',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
