# Generated by Django 4.1.5 on 2023-01-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_aircraft_manufacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='icao_code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
