# Generated by Django 4.1.5 on 2023-01-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_airport_icao_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
